- name: Configure Cisco Router
  hosts: all
  gather_facts: no
  connection: network_cli
  collections:
    - cisco.ios

  tasks:
    - name: Disable paging
      ios_command:
        commands:
          - terminal length 0

    - name: Configure interface and banner
      ios_config:
        lines:
          - configure terminal
          - banner motd ^Authorized Access Only!^
