- name: Configure Cisco Router
  hosts: all
  gather_facts: no
  connection: network_cli
  collections:
    - cisco.nxos

  tasks:
    - name: Run show run
      nxos_command:
        commands:
          - show running
