---
- name: Configure Cisco Router
  hosts: 10.1.1.150
  gather_facts: no
  connection: network_cli              # Force network_cli connection for ios modules
  collections:
    - cisco.ios                      # Ensure the ios_config module is found

  tasks:
    - name: Configure interface and banner
      ios_config:
        lines:
          - banner motd ^Authorized Access Only!^
