- name: Configure Cisco Router
  hosts: all
  gather_facts: no
  connection: network_cli
  collections:
    - cisco.ios

  tasks:
    - name: Disable paging
      ios_command:
        commands:
          - show run
